In [4]:
import numpy as np
import matplotlib as plt
import pandas as pd

In [10]:
# data1=pd.read_excel("H:\\Untitled.xls")
# data1.head()
names=np.array(["bob",'JOe',"will","BOb","JOe","WIll","bob"])

In [11]:
data=np.random.randn(7,4)

In [12]:
names

array(['bob', 'JOe', 'will', 'BOb', 'JOe', 'WIll', 'bob'], dtype='<U4')

In [13]:
data

array([[-1.20055444, -2.10091513, -0.50396043,  0.71259262],
       [ 0.72634043,  1.44535539, -0.68878278,  1.02746639],
       [-0.45133992,  0.63629063, -0.41234029, -0.48236464],
       [-0.4964496 , -0.11048675, -0.10462468,  0.21619413],
       [-1.48606194,  0.124738  , -0.48183112, -0.89265064],
       [ 1.61227223,  0.70699812, -2.01675248,  0.96697489],
       [ 0.54241311, -0.92247638, -0.30754905,  1.74618211]])

In [14]:
names=="bob"

array([ True, False, False, False, False, False,  True])

In [15]:
data[names=='bob']

array([[-1.20055444, -2.10091513, -0.50396043,  0.71259262],
       [ 0.54241311, -0.92247638, -0.30754905,  1.74618211]])

In [16]:
data[~(names=="bob")]

array([[ 0.72634043,  1.44535539, -0.68878278,  1.02746639],
       [-0.45133992,  0.63629063, -0.41234029, -0.48236464],
       [-0.4964496 , -0.11048675, -0.10462468,  0.21619413],
       [-1.48606194,  0.124738  , -0.48183112, -0.89265064],
       [ 1.61227223,  0.70699812, -2.01675248,  0.96697489]])

In [20]:
names!="bob"

array([False,  True,  True,  True,  True,  True, False])

In [21]:
data[1]

array([ 0.72634043,  1.44535539, -0.68878278,  1.02746639])

In [23]:
data[ True]

array([[[-1.20055444, -2.10091513, -0.50396043,  0.71259262],
        [ 0.72634043,  1.44535539, -0.68878278,  1.02746639],
        [-0.45133992,  0.63629063, -0.41234029, -0.48236464],
        [-0.4964496 , -0.11048675, -0.10462468,  0.21619413],
        [-1.48606194,  0.124738  , -0.48183112, -0.89265064],
        [ 1.61227223,  0.70699812, -2.01675248,  0.96697489],
        [ 0.54241311, -0.92247638, -0.30754905,  1.74618211]]])

In [25]:
data[False]

array([], shape=(0, 7, 4), dtype=float64)

mask=(names=="BOb")|(names=="WIll")

In [29]:
mask

array([False, False, False,  True, False,  True, False])

In [30]:
data[mask]

array([[-0.4964496 , -0.11048675, -0.10462468,  0.21619413],
       [ 1.61227223,  0.70699812, -2.01675248,  0.96697489]])

In [31]:
arr=np.arange(32).reshape(8,4)

In [33]:
arr

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15],
       [16, 17, 18, 19],
       [20, 21, 22, 23],
       [24, 25, 26, 27],
       [28, 29, 30, 31]])

# 1.  矩阵

In [39]:
matr1=np.mat("1,2,3;4,5,6;7,8,9")

In [40]:
matr1

matrix([[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]])

In [41]:
matr2=np.matrix([[1,2,3],[4,5,6],[7,8,9]])

In [43]:
matr2

matrix([[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]])

In [44]:
arr=np.eye(3)

In [45]:
arr2=arr*3

In [47]:
np.bmat("arr arr2")

matrix([[1., 0., 0., 3., 0., 0.],
        [0., 1., 0., 0., 3., 0.],
        [0., 0., 1., 0., 0., 3.]])

In [49]:
np.bmat("arr arr2;arr2 arr")

matrix([[1., 0., 0., 3., 0., 0.],
        [0., 1., 0., 0., 3., 0.],
        [0., 0., 1., 0., 0., 3.],
        [3., 0., 0., 1., 0., 0.],
        [0., 3., 0., 0., 1., 0.],
        [0., 0., 3., 0., 0., 1.]])



# 统计分析

In [50]:
points=np.arange(-5,5,0.01)

In [53]:
xs,ys=np.meshgrid(points,points)

In [54]:
xs,ys

(array([[-5.  , -4.99, -4.98, ...,  4.97,  4.98,  4.99],
        [-5.  , -4.99, -4.98, ...,  4.97,  4.98,  4.99],
        [-5.  , -4.99, -4.98, ...,  4.97,  4.98,  4.99],
        ...,
        [-5.  , -4.99, -4.98, ...,  4.97,  4.98,  4.99],
        [-5.  , -4.99, -4.98, ...,  4.97,  4.98,  4.99],
        [-5.  , -4.99, -4.98, ...,  4.97,  4.98,  4.99]]),
 array([[-5.  , -5.  , -5.  , ..., -5.  , -5.  , -5.  ],
        [-4.99, -4.99, -4.99, ..., -4.99, -4.99, -4.99],
        [-4.98, -4.98, -4.98, ..., -4.98, -4.98, -4.98],
        ...,
        [ 4.97,  4.97,  4.97, ...,  4.97,  4.97,  4.97],
        [ 4.98,  4.98,  4.98, ...,  4.98,  4.98,  4.98],
        [ 4.99,  4.99,  4.99, ...,  4.99,  4.99,  4.99]]))

In [55]:
ys

array([[-5.  , -5.  , -5.  , ..., -5.  , -5.  , -5.  ],
       [-4.99, -4.99, -4.99, ..., -4.99, -4.99, -4.99],
       [-4.98, -4.98, -4.98, ..., -4.98, -4.98, -4.98],
       ...,
       [ 4.97,  4.97,  4.97, ...,  4.97,  4.97,  4.97],
       [ 4.98,  4.98,  4.98, ...,  4.98,  4.98,  4.98],
       [ 4.99,  4.99,  4.99, ...,  4.99,  4.99,  4.99]])

In [56]:
xs

array([[-5.  , -4.99, -4.98, ...,  4.97,  4.98,  4.99],
       [-5.  , -4.99, -4.98, ...,  4.97,  4.98,  4.99],
       [-5.  , -4.99, -4.98, ...,  4.97,  4.98,  4.99],
       ...,
       [-5.  , -4.99, -4.98, ...,  4.97,  4.98,  4.99],
       [-5.  , -4.99, -4.98, ...,  4.97,  4.98,  4.99],
       [-5.  , -4.99, -4.98, ...,  4.97,  4.98,  4.99]])

In [57]:
## sqrt(x^2+y^2)
z=np.sqrt(xs**2+ys**2)

In [58]:
z

array([[7.07106781, 7.06400028, 7.05693985, ..., 7.04988652, 7.05693985,
        7.06400028],
       [7.06400028, 7.05692568, 7.04985815, ..., 7.04279774, 7.04985815,
        7.05692568],
       [7.05693985, 7.04985815, 7.04278354, ..., 7.03571603, 7.04278354,
        7.04985815],
       ...,
       [7.04988652, 7.04279774, 7.03571603, ..., 7.0286414 , 7.03571603,
        7.04279774],
       [7.05693985, 7.04985815, 7.04278354, ..., 7.03571603, 7.04278354,
        7.04985815],
       [7.06400028, 7.05692568, 7.04985815, ..., 7.04279774, 7.04985815,
        7.05692568]])

In [76]:
xarry=np.arange(0,5,0.5)
yarry=np.arange(5,10,0.5)

In [79]:
cond=np.array([1,0,1,0,0,1,0,1,0,1])

In [80]:
xarry,yarry,cond

(array([0. , 0.5, 1. , 1.5, 2. , 2.5, 3. , 3.5, 4. , 4.5]),
 array([5. , 5.5, 6. , 6.5, 7. , 7.5, 8. , 8.5, 9. , 9.5]),
 array([1, 0, 1, 0, 0, 1, 0, 1, 0, 1]))

In [81]:
print(len(cond),len(xarry),len(yarry))

10 10 10


In [82]:
result=[x if c else y
        for x,y,c in zip(xarry,yarry,cond)]

In [83]:
result

[0.0, 5.5, 1.0, 6.5, 7.0, 2.5, 8.0, 3.5, 9.0, 4.5]

In [84]:
result1=np.where(cond,xarry,yarry)

In [85]:
result1

array([0. , 5.5, 1. , 6.5, 7. , 2.5, 8. , 3.5, 9. , 4.5])

In [86]:
arr=np.random.randn(5,4)

In [87]:
arr

array([[-0.74225246, -0.49241197, -1.98794026,  1.92950548],
       [ 0.02037603,  0.02593824,  1.13256184, -0.23860464],
       [ 1.35475723, -0.91981036, -0.88466525,  0.13067187],
       [-0.99088938, -0.49613526,  0.8610117 , -0.99473433],
       [-0.20717439, -2.32094888,  0.20396579,  0.82629964]])

In [88]:
np.where(arr>0,2,0)

array([[0, 0, 0, 2],
       [2, 2, 2, 0],
       [2, 0, 0, 2],
       [0, 0, 2, 0],
       [0, 0, 2, 2]])

In [89]:
arr.mean()

-0.18952396770541619

In [92]:
arr.std()

1.0412662820097334

In [6]:
y=np.arange(5,10,0.5)
x=np.arange(0,5,0.5)

In [7]:
x,y

(array([0. , 0.5, 1. , 1.5, 2. , 2.5, 3. , 3.5, 4. , 4.5]),
 array([5. , 5.5, 6. , 6.5, 7. , 7.5, 8. , 8.5, 9. , 9.5]))

In [8]:
np.meshgrid(x,y)

[array([[0. , 0.5, 1. , 1.5, 2. , 2.5, 3. , 3.5, 4. , 4.5],
        [0. , 0.5, 1. , 1.5, 2. , 2.5, 3. , 3.5, 4. , 4.5],
        [0. , 0.5, 1. , 1.5, 2. , 2.5, 3. , 3.5, 4. , 4.5],
        [0. , 0.5, 1. , 1.5, 2. , 2.5, 3. , 3.5, 4. , 4.5],
        [0. , 0.5, 1. , 1.5, 2. , 2.5, 3. , 3.5, 4. , 4.5],
        [0. , 0.5, 1. , 1.5, 2. , 2.5, 3. , 3.5, 4. , 4.5],
        [0. , 0.5, 1. , 1.5, 2. , 2.5, 3. , 3.5, 4. , 4.5],
        [0. , 0.5, 1. , 1.5, 2. , 2.5, 3. , 3.5, 4. , 4.5],
        [0. , 0.5, 1. , 1.5, 2. , 2.5, 3. , 3.5, 4. , 4.5],
        [0. , 0.5, 1. , 1.5, 2. , 2.5, 3. , 3.5, 4. , 4.5]]),
 array([[5. , 5. , 5. , 5. , 5. , 5. , 5. , 5. , 5. , 5. ],
        [5.5, 5.5, 5.5, 5.5, 5.5, 5.5, 5.5, 5.5, 5.5, 5.5],
        [6. , 6. , 6. , 6. , 6. , 6. , 6. , 6. , 6. , 6. ],
        [6.5, 6.5, 6.5, 6.5, 6.5, 6.5, 6.5, 6.5, 6.5, 6.5],
        [7. , 7. , 7. , 7. , 7. , 7. , 7. , 7. , 7. , 7. ],
        [7.5, 7.5, 7.5, 7.5, 7.5, 7.5, 7.5, 7.5, 7.5, 7.5],
        [8. , 8. , 8. , 8. , 8. , 8. ,

In [14]:
xm=np.meshgrid(x,y)

In [15]:
xm

[array([[0. , 0.5, 1. , 1.5, 2. , 2.5, 3. , 3.5, 4. , 4.5],
        [0. , 0.5, 1. , 1.5, 2. , 2.5, 3. , 3.5, 4. , 4.5],
        [0. , 0.5, 1. , 1.5, 2. , 2.5, 3. , 3.5, 4. , 4.5],
        [0. , 0.5, 1. , 1.5, 2. , 2.5, 3. , 3.5, 4. , 4.5],
        [0. , 0.5, 1. , 1.5, 2. , 2.5, 3. , 3.5, 4. , 4.5],
        [0. , 0.5, 1. , 1.5, 2. , 2.5, 3. , 3.5, 4. , 4.5],
        [0. , 0.5, 1. , 1.5, 2. , 2.5, 3. , 3.5, 4. , 4.5],
        [0. , 0.5, 1. , 1.5, 2. , 2.5, 3. , 3.5, 4. , 4.5],
        [0. , 0.5, 1. , 1.5, 2. , 2.5, 3. , 3.5, 4. , 4.5],
        [0. , 0.5, 1. , 1.5, 2. , 2.5, 3. , 3.5, 4. , 4.5]]),
 array([[5. , 5. , 5. , 5. , 5. , 5. , 5. , 5. , 5. , 5. ],
        [5.5, 5.5, 5.5, 5.5, 5.5, 5.5, 5.5, 5.5, 5.5, 5.5],
        [6. , 6. , 6. , 6. , 6. , 6. , 6. , 6. , 6. , 6. ],
        [6.5, 6.5, 6.5, 6.5, 6.5, 6.5, 6.5, 6.5, 6.5, 6.5],
        [7. , 7. , 7. , 7. , 7. , 7. , 7. , 7. , 7. , 7. ],
        [7.5, 7.5, 7.5, 7.5, 7.5, 7.5, 7.5, 7.5, 7.5, 7.5],
        [8. , 8. , 8. , 8. , 8. , 8. ,

In [16]:
xm,ym=np.meshgrid(x,y)

In [17]:
xm

array([[0. , 0.5, 1. , 1.5, 2. , 2.5, 3. , 3.5, 4. , 4.5],
       [0. , 0.5, 1. , 1.5, 2. , 2.5, 3. , 3.5, 4. , 4.5],
       [0. , 0.5, 1. , 1.5, 2. , 2.5, 3. , 3.5, 4. , 4.5],
       [0. , 0.5, 1. , 1.5, 2. , 2.5, 3. , 3.5, 4. , 4.5],
       [0. , 0.5, 1. , 1.5, 2. , 2.5, 3. , 3.5, 4. , 4.5],
       [0. , 0.5, 1. , 1.5, 2. , 2.5, 3. , 3.5, 4. , 4.5],
       [0. , 0.5, 1. , 1.5, 2. , 2.5, 3. , 3.5, 4. , 4.5],
       [0. , 0.5, 1. , 1.5, 2. , 2.5, 3. , 3.5, 4. , 4.5],
       [0. , 0.5, 1. , 1.5, 2. , 2.5, 3. , 3.5, 4. , 4.5],
       [0. , 0.5, 1. , 1.5, 2. , 2.5, 3. , 3.5, 4. , 4.5]])

In [18]:
data=pd.read_excel("H://wait_data/CEB.xlsx")

In [19]:
data.head()

short_       date  incoming  Settlement  PV    UV  profit
0  mqs3b2-F 2020-01-01         1           0  341  309       0
1   mqc22-H 2020-01-01         9           3  594  547     420
2  mqs3b2-F 2020-01-02         9           2  431  373     280
3   mqc22-H 2020-01-02         0           3  801  734     420
4  mqs3b2-F 2020-01-03         7           1  430  376     140

In [21]:
type(data["date"])

pandas.core.series.Series

In [22]:
feature=pd.DataFrame(data)

In [23]:
print(type(feature),type(data))

<class 'pandas.core.frame.DataFrame'> <class 'pandas.core.frame.DataFrame'>
