In [6]:
val='z,d, guido'

In [7]:
val.split(",")

['z', 'd', ' guido']

In [8]:
pieces=[x.strip() for x in val.split(",")] # split常和strip一起使用，用于清除空格（包括换行）：
pieces

['z', 'd', 'guido']

In [9]:
"::".join(pieces)

'z::d::guido'

In [10]:
"z" in val

True

In [12]:
val.index(",")

1

In [13]:
val.count(",")

2

In [14]:
val.capitalize()

'Z,d, guido'

In [19]:
val.center(1)

'z,d, guido'

In [20]:
val.replace(",",":::")

'z:::d::: guido'

# 联合索引


In [36]:
import pandas as pd
df1=pd.DataFrame({"key":['a','d','d','b','a','c','d'],"data":range(7)})
df2=pd.DataFrame({"key":['a','d','b'],"data":range(3)})             
print(df1,df2)

  key  data
0   a     0
1   d     1
2   d     2
3   b     3
4   a     4
5   c     5
6   d     6   key  data
0   a     0
1   d     1
2   b     2


In [37]:
df1.merge(df2) # 并没有指定在哪一列上进行连接。如果连接的键信息没有指定，merge会自动将重叠列名作为连接的键

key  data
0   a     0
1   d     1

In [38]:
pd.merge(df1,df2,on="key")

key  data_x  data_y
0   a       0       0
1   a       4       0
2   d       1       1
3   d       2       1
4   d       6       1
5   b       3       2

In [39]:
df3=pd.DataFrame({"key1":['a','d','d','b','a','c','d'],"data1":range(7)})
df4=pd.DataFrame({"key2":['a','d','b'],"data2":range(3)})   
print(df3,df4)

  key1  data1
0    a      0
1    d      1
2    d      2
3    b      3
4    a      4
5    c      5
6    d      6   key2  data2
0    a      0
1    d      1
2    b      2


In [40]:
pd.merge(df3,df4,right_on="key2",left_on="key1")

key1  data1 key2  data2
0    a      0    a      0
1    a      4    a      0
2    d      1    d      1
3    d      2    d      1
4    d      6    d      1
5    b      3    b      2

In [41]:
pd.merge(df1,df2,how="outer")  # 默认情况下，merge做的是内连接（’inner’join），结果中的键是两张表的交集。其他可选的选项有’left’、’right’和’outer’。外连接（outer join）是键的并集，联合了左连接和右连接的效果

key  data
0   a     0
1   d     1
2   d     2
3   b     3
4   a     4
5   c     5
6   d     6
7   b     2

In [42]:
df5=pd.DataFrame({"key":['a','d','d','b','a','c'],"data1":range(6)})
df6=pd.DataFrame({"group_val":[3.5,7]},index=['a','d'])   

In [43]:
pd.merge(df5,df6,left_on="key",right_index=True,how="outer")

key  data1  group_val
0   a      0        3.5
4   a      4        3.5
1   d      1        7.0
2   d      2        7.0
3   b      3        NaN
5   c      5        NaN

In [44]:
import numpy as np
arr=np.arange(12).reshape((3,4))
arr

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [45]:
np.concatenate([arr,arr],axis=1)


array([[ 0,  1,  2,  3,  0,  1,  2,  3],
       [ 4,  5,  6,  7,  4,  5,  6,  7],
       [ 8,  9, 10, 11,  8,  9, 10, 11]])

In [46]:
np.concatenate([arr,arr],axis=0)

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [48]:
pd.concat([df1,df2])

key  data
0   a     0
1   d     1
2   d     2
3   b     3
4   a     4
5   c     5
6   d     6
0   a     0
1   d     1
2   b     2

In [52]:
pd.concat([df1,df2],axis=1,join="inner")

key  data key  data
0   a     0   a     0
1   d     1   d     1
2   d     2   b     2

# 分层索引

In [82]:
data=pd.Series(np.arange(9),index=[['a','d','d','b','a','c','c','a','b'],[1,3,2,3,2,2,1,3,2]])
data

a  1    0
d  3    1
   2    2
b  3    3
a  2    4
c  2    5
   1    6
a  3    7
b  2    8
dtype: int32

In [85]:
list(set(data.index))

[('a', 2),
 ('a', 3),
 ('c', 2),
 ('b', 2),
 ('b', 3),
 ('a', 1),
 ('c', 1),
 ('d', 2),
 ('d', 3)]

In [77]:
data['b']

3    3
2    8
dtype: int32

In [78]:
# data["b":"a"]

In [79]:
data.loc[["b","d"]]

d  3    1
   2    2
b  3    3
   2    8
dtype: int32

In [80]:
data.loc[:,1]#  第二个参数是指index值为1的  并不是步长。

a    0
c    6
dtype: int32

In [87]:
data.unstack()

1    2    3
a  0.0  4.0  7.0
b  NaN  8.0  3.0
c  6.0  5.0  NaN
d  NaN  2.0  1.0

In [88]:
data.unstack().stack()

a  1    0.0
   2    4.0
   3    7.0
b  2    8.0
   3    3.0
c  1    6.0
   2    5.0
d  2    2.0
   3    1.0
dtype: float64

In [89]:
data

a  1    0
d  3    1
   2    2
b  3    3
a  2    4
c  2    5
   1    6
a  3    7
b  2    8
dtype: int32

In [97]:
data1=pd.DataFrame(np.arange(12).reshape(4,3),
                   index=[['a','a','d','d'],[1,2,1,2]],
                   columns=[["name",'name',"age"],["G","B","R"]])
data1

name     age
       G   B   R
a 1    0   1   2
  2    3   4   5
d 1    6   7   8
  2    9  10  11

In [98]:
data1.loc["a"]

name    age
     G  B   R
1    0  1   2
2    3  4   5

In [101]:
data1.index.names=["key1","key2"]
data1.columns.names=["state","color"]

In [102]:
data1

state     name     age
color        G   B   R
key1 key2             
a    1       0   1   2
     2       3   4   5
d    1       6   7   8
     2       9  10  11

In [104]:
data1["name"]

color      G   B
key1 key2       
a    1     0   1
     2     3   4
d    1     6   7
     2     9  10

In [105]:
data1.unstack()

state name           age    
color    G     B       R    
key2     1  2  1   2   1   2
key1                        
a        0  3  1   4   2   5
d        6  9  7  10   8  11

In [106]:
data1.unstack().stack()

state     age name   
color       R    B  G
key1 key2            
a    1      2    1  0
     2      5    4  3
d    1      8    7  6
     2     11   10  9

In [107]:
data1.swaplevel()

state     name     age
color        G   B   R
key2 key1             
1    a       0   1   2
2    a       3   4   5
1    d       6   7   8
2    d       9  10  11

In [116]:
data1.sort_index(level=1)  #   level 指的是index的值的索引

state     name     age
color        G   B   R
key1 key2             
a    1       0   1   2
d    1       6   7   8
a    2       3   4   5
d    2       9  10  11

In [124]:
data1.sort_index(level=1,axis=1)  

state     name    age
color        B  G   R
key1 key2            
a    1       1  0   2
     2       4  3   5
d    1       7  6   8
     2      10  9  11

In [122]:
data1.sum(level=1)

state name     age
color    G   B   R
key2              
1        6   8  10
2       12  14  16

In [123]:
data1.sum(level="state",axis=1)

state      name  age
key1 key2           
a    1        1    2
     2        7    5
d    1       13    8
     2       19   11

In [132]:
data2=pd.DataFrame({'a':range(7),"b":range(7,0,-1),"c":["one","one","one","one","two","two","two"],"d":[1,1,2,3,4,1,3]})
data2

a  b    c  d
0  0  7  one  1
1  1  6  one  1
2  2  5  one  2
3  3  4  one  3
4  4  3  two  4
5  5  2  two  1
6  6  1  two  3

In [133]:
data2.set_index("c")

a  b  d
c           
one  0  7  1
one  1  6  1
one  2  5  2
one  3  4  3
two  4  3  4
two  5  2  1
two  6  1  3

In [136]:
data2.set_index(["c","d"])

a  b
c   d      
one 1  0  7
    1  1  6
    2  2  5
    3  3  4
two 4  4  3
    1  5  2
    3  6  1

In [139]:
melted=pd.melt(data2,["a"])
melted

a variable value
0   0        b     7
1   1        b     6
2   2        b     5
3   3        b     4
4   4        b     3
5   5        b     2
6   6        b     1
7   0        c   one
8   1        c   one
9   2        c   one
10  3        c   one
11  4        c   two
12  5        c   two
13  6        c   two
14  0        d     1
15  1        d     1
16  2        d     2
17  3        d     3
18  4        d     4
19  5        d     1
20  6        d     3

In [140]:
melted.pivot("a","variable","value")

variable  b    c  d
a                  
0         7  one  1
1         6  one  1
2         5  one  2
3         4  one  3
4         3  two  4
5         2  two  1
6         1  two  3

In [141]:
melted.pivot("a","variable","value").reset_index()

variable  a  b    c  d
0         0  7  one  1
1         1  6  one  1
2         2  5  one  2
3         3  4  one  3
4         4  3  two  4
5         5  2  two  1
6         6  1  two  3